# Form implementation generated from reading ui file 'PyQt6\Mega_Project_GUI\mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 586)
        MainWindow.setMinimumSize(QtCore.QSize(805, 586))
        MainWindow.setMaximumSize(QtCore.QSize(805, 586))
        MainWindow.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0648899 rgba(9, 15, 19, 255), stop:0.571233 rgba(21, 59, 71, 255), stop:0.890411 rgba(61, 96, 110, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.maintabs_Widget = QtWidgets.QTabWidget(parent=self.centralwidget)
        palette = QtGui.QPalette()
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0648899, QtGui.QColor(9, 15, 19))
        gradient.setColorAt(0.571233, QtGui.QColor(21, 59, 71))
        gradient.setColorAt(0.890411, QtGui.QColor(61, 96, 110))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0648899, QtGui.QColor(9, 15, 19))
        gradient.setColorAt(0.571233, QtGui.QColor(21, 59, 71))
        gradient.setColorAt(0.890411, QtGui.QColor(61, 96, 110))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0648899, QtGui.QColor(9, 15, 19))
        gradient.setColorAt(0.571233, QtGui.QColor(21, 59, 71))
        gradient.setColorAt(0.890411, QtGui.QColor(61, 96, 110))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0648899, QtGui.QColor(9, 15, 19))
        gradient.setColorAt(0.571233, QtGui.QColor(21, 59, 71))
        gradient.setColorAt(0.890411, QtGui.QColor(61, 96, 110))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0648899, QtGui.QColor(9, 15, 19))
        gradient.setColorAt(0.571233, QtGui.QColor(21, 59, 71))
        gradient.setColorAt(0.890411, QtGui.QColor(61, 96, 110))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0648899, QtGui.QColor(9, 15, 19))
        gradient.setColorAt(0.571233, QtGui.QColor(21, 59, 71))
        gradient.setColorAt(0.890411, QtGui.QColor(61, 96, 110))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0648899, QtGui.QColor(9, 15, 19))
        gradient.setColorAt(0.571233, QtGui.QColor(21, 59, 71))
        gradient.setColorAt(0.890411, QtGui.QColor(61, 96, 110))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0648899, QtGui.QColor(9, 15, 19))
        gradient.setColorAt(0.571233, QtGui.QColor(21, 59, 71))
        gradient.setColorAt(0.890411, QtGui.QColor(61, 96, 110))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0.0648899, QtGui.QColor(9, 15, 19))
        gradient.setColorAt(0.571233, QtGui.QColor(21, 59, 71))
        gradient.setColorAt(0.890411, QtGui.QColor(61, 96, 110))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.maintabs_Widget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.maintabs_Widget.setFont(font)
        self.maintabs_Widget.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.maintabs_Widget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.maintabs_Widget.setAutoFillBackground(False)
        self.maintabs_Widget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.maintabs_Widget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.maintabs_Widget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.maintabs_Widget.setDocumentMode(True)
        self.maintabs_Widget.setObjectName("maintabs_Widget")
        self.home_tab = QtWidgets.QWidget()
        self.home_tab.setObjectName("home_tab")
        self.StereoVision_pushButton_frame = QtWidgets.QFrame(parent=self.home_tab)
        self.StereoVision_pushButton_frame.setGeometry(QtCore.QRect(450, 290, 320, 170))
        self.StereoVision_pushButton_frame.setMinimumSize(QtCore.QSize(320, 170))
        self.StereoVision_pushButton_frame.setStyleSheet("background-color:#3d606e;\n"
"border-radius:80px")
        self.StereoVision_pushButton_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.StereoVision_pushButton_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.StereoVision_pushButton_frame.setObjectName("StereoVision_pushButton_frame")
        self.StereoVision_pushButton = QtWidgets.QPushButton(parent=self.StereoVision_pushButton_frame)
        self.StereoVision_pushButton.setGeometry(QtCore.QRect(10, 10, 300, 150))
        self.StereoVision_pushButton.setMinimumSize(QtCore.QSize(300, 150))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.StereoVision_pushButton.setFont(font)
        self.StereoVision_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:70px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(230, 176, 38);\n"
"}")
        self.StereoVision_pushButton.setCheckable(False)
        self.StereoVision_pushButton.setObjectName("StereoVision_pushButton")
        self.credits_pushButton = QtWidgets.QPushButton(parent=self.home_tab)
        self.credits_pushButton.setGeometry(QtCore.QRect(370, 490, 81, 31))
        self.credits_pushButton.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setBold(True)
        self.credits_pushButton.setFont(font)
        self.credits_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(61, 96, 110);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(230, 176, 38);\n"
"}")
        self.credits_pushButton.setObjectName("credits_pushButton")
        self.videoStitching_pushButton_frame = QtWidgets.QFrame(parent=self.home_tab)
        self.videoStitching_pushButton_frame.setGeometry(QtCore.QRect(50, 290, 320, 170))
        self.videoStitching_pushButton_frame.setMinimumSize(QtCore.QSize(320, 170))
        self.videoStitching_pushButton_frame.setStyleSheet("background-color:#3d606e;\n"
"border-radius:80px;")
        self.videoStitching_pushButton_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.videoStitching_pushButton_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.videoStitching_pushButton_frame.setObjectName("videoStitching_pushButton_frame")
        self.videoStitching_pushButton = QtWidgets.QPushButton(parent=self.videoStitching_pushButton_frame)
        self.videoStitching_pushButton.setGeometry(QtCore.QRect(10, 10, 300, 150))
        self.videoStitching_pushButton.setMinimumSize(QtCore.QSize(300, 150))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.videoStitching_pushButton.setFont(font)
        self.videoStitching_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"color: rgb(255, 255, 255);\n"
"border-radius:70px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(230, 176, 38);\n"
"}")
        self.videoStitching_pushButton.setCheckable(False)
        self.videoStitching_pushButton.setObjectName("videoStitching_pushButton")
        self.welcome_frame = QtWidgets.QFrame(parent=self.home_tab)
        self.welcome_frame.setGeometry(QtCore.QRect(170, 20, 461, 50))
        self.welcome_frame.setMinimumSize(QtCore.QSize(460, 0))
        self.welcome_frame.setStyleSheet("background-color: rgb(61, 96, 110);\n"
"border-radius:15px;")
        self.welcome_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.welcome_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.welcome_frame.setObjectName("welcome_frame")
        self.welcome_label = QtWidgets.QLabel(parent=self.welcome_frame)
        self.welcome_label.setGeometry(QtCore.QRect(20, 0, 421, 50))
        self.welcome_label.setMinimumSize(QtCore.QSize(420, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.welcome_label.setFont(font)
        self.welcome_label.setStyleSheet("color:white;")
        self.welcome_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.welcome_label.setObjectName("welcome_label")
        self.aquaphoton_logo_label = QtWidgets.QLabel(parent=self.home_tab)
        self.aquaphoton_logo_label.setGeometry(QtCore.QRect(160, 90, 481, 181))
        self.aquaphoton_logo_label.setMinimumSize(QtCore.QSize(480, 180))
        self.aquaphoton_logo_label.setStyleSheet("background:none;")
        self.aquaphoton_logo_label.setText("")
        self.aquaphoton_logo_label.setPixmap(QtGui.QPixmap("PyQt6\\Mega_Project_GUI\\icons\\aqua_logo.png"))
        self.aquaphoton_logo_label.setScaledContents(True)
        self.aquaphoton_logo_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.aquaphoton_logo_label.setObjectName("aquaphoton_logo_label")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("PyQt6\\Mega_Project_GUI\\icons\\home_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("PyQt6\\Mega_Project_GUI\\icons\\home_icon2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.maintabs_Widget.addTab(self.home_tab, icon, "")
        self.control_tab = QtWidgets.QWidget()
        self.control_tab.setObjectName("control_tab")
        self.mode_frame = QtWidgets.QFrame(parent=self.control_tab)
        self.mode_frame.setGeometry(QtCore.QRect(40, 380, 160, 160))
        self.mode_frame.setStyleSheet("background-color:#3d606e;\n"
"border-radius:50px;")
        self.mode_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.mode_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.mode_frame.setObjectName("mode_frame")
        self.mode_label = QtWidgets.QLabel(parent=self.mode_frame)
        self.mode_label.setGeometry(QtCore.QRect(10, 20, 140, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.mode_label.setFont(font)
        self.mode_label.setStyleSheet("background:none;\n"
"color:white;\n"
"")
        self.mode_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mode_label.setObjectName("mode_label")
        self.autonomus_mode_pushButton = QtWidgets.QPushButton(parent=self.mode_frame)
        self.autonomus_mode_pushButton.setGeometry(QtCore.QRect(30, 60, 90, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.autonomus_mode_pushButton.setFont(font)
        self.autonomus_mode_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.autonomus_mode_pushButton.setCheckable(True)
        self.autonomus_mode_pushButton.setAutoExclusive(True)
        self.autonomus_mode_pushButton.setObjectName("autonomus_mode_pushButton")
        self.manual_mode_pushButton = QtWidgets.QPushButton(parent=self.mode_frame)
        self.manual_mode_pushButton.setGeometry(QtCore.QRect(30, 110, 90, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.manual_mode_pushButton.setFont(font)
        self.manual_mode_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: rgb(230, 176, 38);\n"
"}")
        self.manual_mode_pushButton.setCheckable(True)
        self.manual_mode_pushButton.setAutoExclusive(True)
        self.manual_mode_pushButton.setObjectName("manual_mode_pushButton")
        self.speed_frame = QtWidgets.QFrame(parent=self.control_tab)
        self.speed_frame.setGeometry(QtCore.QRect(610, 20, 160, 221))
        self.speed_frame.setStyleSheet("background-color:#3d606e;\n"
"border-radius:50px;")
        self.speed_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.speed_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.speed_frame.setObjectName("speed_frame")
        self.select_speed_label = QtWidgets.QLabel(parent=self.speed_frame)
        self.select_speed_label.setGeometry(QtCore.QRect(10, 20, 140, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.select_speed_label.setFont(font)
        self.select_speed_label.setStyleSheet("color:white;")
        self.select_speed_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.select_speed_label.setObjectName("select_speed_label")
        self.high_speed_pushButton = QtWidgets.QPushButton(parent=self.speed_frame)
        self.high_speed_pushButton.setGeometry(QtCore.QRect(30, 60, 90, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.high_speed_pushButton.setFont(font)
        self.high_speed_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.high_speed_pushButton.setCheckable(True)
        self.high_speed_pushButton.setAutoExclusive(True)
        self.high_speed_pushButton.setObjectName("high_speed_pushButton")
        self.medium_speed_pushButton = QtWidgets.QPushButton(parent=self.speed_frame)
        self.medium_speed_pushButton.setGeometry(QtCore.QRect(30, 110, 90, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.medium_speed_pushButton.setFont(font)
        self.medium_speed_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.medium_speed_pushButton.setCheckable(True)
        self.medium_speed_pushButton.setAutoExclusive(True)
        self.medium_speed_pushButton.setObjectName("medium_speed_pushButton")
        self.low_speed_pushButton = QtWidgets.QPushButton(parent=self.speed_frame)
        self.low_speed_pushButton.setGeometry(QtCore.QRect(30, 160, 90, 40))
        font = QtGui.QFont()
        font.setBold(True)
        self.low_speed_pushButton.setFont(font)
        self.low_speed_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.low_speed_pushButton.setCheckable(True)
        self.low_speed_pushButton.setAutoExclusive(True)
        self.low_speed_pushButton.setObjectName("low_speed_pushButton")
        self.select_controller_frame = QtWidgets.QFrame(parent=self.control_tab)
        self.select_controller_frame.setGeometry(QtCore.QRect(520, 380, 251, 160))
        self.select_controller_frame.setStyleSheet("background-color:#3d606e;\n"
"border-radius:60px;")
        self.select_controller_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.select_controller_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.select_controller_frame.setObjectName("select_controller_frame")
        self.select_controller_label = QtWidgets.QLabel(parent=self.select_controller_frame)
        self.select_controller_label.setGeometry(QtCore.QRect(40, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.select_controller_label.setFont(font)
        self.select_controller_label.setStyleSheet("color:white;")
        self.select_controller_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.select_controller_label.setObjectName("select_controller_label")
        self.keyboard_pushButton = QtWidgets.QPushButton(parent=self.select_controller_frame)
        self.keyboard_pushButton.setGeometry(QtCore.QRect(69, 50, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.keyboard_pushButton.setFont(font)
        self.keyboard_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.keyboard_pushButton.setCheckable(True)
        self.keyboard_pushButton.setAutoExclusive(True)
        self.keyboard_pushButton.setObjectName("keyboard_pushButton")
        self.GUI_pushButton = QtWidgets.QPushButton(parent=self.select_controller_frame)
        self.GUI_pushButton.setGeometry(QtCore.QRect(70, 110, 110, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.GUI_pushButton.setFont(font)
        self.GUI_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"color:white;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.GUI_pushButton.setCheckable(True)
        self.GUI_pushButton.setAutoExclusive(True)
        self.GUI_pushButton.setObjectName("GUI_pushButton")
        self.indicators_back_frame = QtWidgets.QFrame(parent=self.control_tab)
        self.indicators_back_frame.setGeometry(QtCore.QRect(30, 20, 551, 331))
        self.indicators_back_frame.setStyleSheet("background-color:#3d606e;\n"
"border-radius:50px;")
        self.indicators_back_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.indicators_back_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.indicators_back_frame.setObjectName("indicators_back_frame")
        self.indicators_front_frame = QtWidgets.QFrame(parent=self.indicators_back_frame)
        self.indicators_front_frame.setGeometry(QtCore.QRect(20, 30, 511, 281))
        self.indicators_front_frame.setStyleSheet("background-color:#153b47;\n"
"border-radius:20px\n"
"")
        self.indicators_front_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.indicators_front_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.indicators_front_frame.setObjectName("indicators_front_frame")
        self.voltage_label = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.voltage_label.setGeometry(QtCore.QRect(18, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.voltage_label.setFont(font)
        self.voltage_label.setStyleSheet("color:white;")
        self.voltage_label.setObjectName("voltage_label")
        self.current_label = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.current_label.setGeometry(QtCore.QRect(18, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.current_label.setFont(font)
        self.current_label.setStyleSheet("color:white;")
        self.current_label.setObjectName("current_label")
        self.line = QtWidgets.QFrame(parent=self.indicators_front_frame)
        self.line.setGeometry(QtCore.QRect(10, 140, 150, 4))
        self.line.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"border-radius:2px;")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.speen_label = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.speen_label.setGeometry(QtCore.QRect(20, 160, 68, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.speen_label.setFont(font)
        self.speen_label.setStyleSheet("color:white;")
        self.speen_label.setObjectName("speen_label")
        self.speed_reading = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.speed_reading.setGeometry(QtCore.QRect(90, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.speed_reading.setFont(font)
        self.speed_reading.setStyleSheet("background-color: rgb(9, 15, 19);\n"
"border-radius: 15px;\n"
"color:white;")
        self.speed_reading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.speed_reading.setObjectName("speed_reading")
        self.mode_indicator = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.mode_indicator.setGeometry(QtCore.QRect(20, 230, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.mode_indicator.setFont(font)
        self.mode_indicator.setStyleSheet("color:white;")
        self.mode_indicator.setObjectName("mode_indicator")
        self.line_2 = QtWidgets.QFrame(parent=self.indicators_front_frame)
        self.line_2.setGeometry(QtCore.QRect(10, 210, 150, 4))
        self.line_2.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"border-radius:2px;")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.mode_reading = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.mode_reading.setGeometry(QtCore.QRect(90, 230, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.mode_reading.setFont(font)
        self.mode_reading.setStyleSheet("background-color: rgb(9, 15, 19);\n"
"border-radius: 15px;\n"
"color:white;")
        self.mode_reading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mode_reading.setObjectName("mode_reading")
        self.voltage_reading = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.voltage_reading.setGeometry(QtCore.QRect(95, 42, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.voltage_reading.setFont(font)
        self.voltage_reading.setStyleSheet("background-color: rgb(9, 15, 19);\n"
"border-radius: 15px;\n"
"color:white;")
        self.voltage_reading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.voltage_reading.setObjectName("voltage_reading")
        self.current_reading = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.current_reading.setGeometry(QtCore.QRect(95, 82, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.current_reading.setFont(font)
        self.current_reading.setStyleSheet("background-color: rgb(9, 15, 19);\n"
"border-radius: 15px;\n"
"color:white;")
        self.current_reading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.current_reading.setObjectName("current_reading")
        self.line_3 = QtWidgets.QFrame(parent=self.indicators_front_frame)
        self.line_3.setGeometry(QtCore.QRect(210, 40, 4, 220))
        self.line_3.setStyleSheet("background-color: rgb(223, 223, 223);\n"
"border-radius:2px;")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.distance_label = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.distance_label.setGeometry(QtCore.QRect(270, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.distance_label.setFont(font)
        self.distance_label.setStyleSheet("color:white;")
        self.distance_label.setObjectName("distance_label")
        self.direction_label = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.direction_label.setGeometry(QtCore.QRect(270, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.direction_label.setFont(font)
        self.direction_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.direction_label.setObjectName("direction_label")
        self.direction_reading = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.direction_reading.setGeometry(QtCore.QRect(360, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.direction_reading.setFont(font)
        self.direction_reading.setStyleSheet("background-color: rgb(9, 15, 19);\n"
"border-radius: 15px;\n"
"color:white;")
        self.direction_reading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.direction_reading.setObjectName("direction_reading")
        self.distance_reading = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.distance_reading.setGeometry(QtCore.QRect(355, 52, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.distance_reading.setFont(font)
        self.distance_reading.setStyleSheet("background-color: rgb(9, 15, 19);\n"
"border-radius: 15px;\n"
"color:white;")
        self.distance_reading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.distance_reading.setObjectName("distance_reading")
        self.connection_label = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.connection_label.setGeometry(QtCore.QRect(270, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.connection_label.setFont(font)
        self.connection_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.connection_label.setObjectName("connection_label")
        self.controller_label = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.controller_label.setGeometry(QtCore.QRect(270, 210, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.controller_label.setFont(font)
        self.controller_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.controller_label.setObjectName("controller_label")
        self.connection_reading = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.connection_reading.setGeometry(QtCore.QRect(380, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.connection_reading.setFont(font)
        self.connection_reading.setStyleSheet("background-color: rgb(9, 15, 19);\n"
"border-radius: 15px;\n"
"color:white;")
        self.connection_reading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.connection_reading.setObjectName("connection_reading")
        self.controller_reading = QtWidgets.QLabel(parent=self.indicators_front_frame)
        self.controller_reading.setGeometry(QtCore.QRect(370, 210, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.controller_reading.setFont(font)
        self.controller_reading.setStyleSheet("background-color: rgb(9, 15, 19);\n"
"border-radius: 15px;\n"
"color:white;")
        self.controller_reading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.controller_reading.setObjectName("controller_reading")
        self.indicators_label_frame = QtWidgets.QFrame(parent=self.indicators_back_frame)
        self.indicators_label_frame.setGeometry(QtCore.QRect(50, 5, 141, 41))
        self.indicators_label_frame.setStyleSheet("border-radius:20px;")
        self.indicators_label_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.indicators_label_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.indicators_label_frame.setObjectName("indicators_label_frame")
        self.indicator_label = QtWidgets.QLabel(parent=self.indicators_label_frame)
        self.indicator_label.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.indicator_label.setFont(font)
        self.indicator_label.setStyleSheet("color:white;")
        self.indicator_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.indicator_label.setObjectName("indicator_label")
        self.movement_frame = QtWidgets.QFrame(parent=self.control_tab)
        self.movement_frame.setGeometry(QtCore.QRect(260, 370, 191, 171))
        self.movement_frame.setStyleSheet("QFrame{\n"
"background-color:#3d606e;\n"
"border-radius:60px;\n"
"}\n"
"")
        self.movement_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.movement_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.movement_frame.setObjectName("movement_frame")
        self.forward_pushButton = QtWidgets.QPushButton(parent=self.movement_frame)
        self.forward_pushButton.setGeometry(QtCore.QRect(70, 10, 50, 50))
        self.forward_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.forward_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("PyQt6\\Mega_Project_GUI\\icons\\arrow_up.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.forward_pushButton.setIcon(icon1)
        self.forward_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.forward_pushButton.setCheckable(False)
        self.forward_pushButton.setAutoExclusive(False)
        self.forward_pushButton.setObjectName("forward_pushButton")
        self.backward_pushButton = QtWidgets.QPushButton(parent=self.movement_frame)
        self.backward_pushButton.setGeometry(QtCore.QRect(70, 110, 50, 50))
        self.backward_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.backward_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("PyQt6\\Mega_Project_GUI\\icons\\arrow_down.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.backward_pushButton.setIcon(icon2)
        self.backward_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.backward_pushButton.setCheckable(False)
        self.backward_pushButton.setAutoExclusive(False)
        self.backward_pushButton.setObjectName("backward_pushButton")
        self.right_pushButton = QtWidgets.QPushButton(parent=self.movement_frame)
        self.right_pushButton.setGeometry(QtCore.QRect(120, 60, 50, 50))
        self.right_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.right_pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("PyQt6\\Mega_Project_GUI\\icons\\arrow_right.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.right_pushButton.setIcon(icon3)
        self.right_pushButton.setIconSize(QtCore.QSize(24, 24))
        self.right_pushButton.setCheckable(False)
        self.right_pushButton.setChecked(False)
        self.right_pushButton.setAutoExclusive(False)
        self.right_pushButton.setObjectName("right_pushButton")
        self.left_pushButton = QtWidgets.QPushButton(parent=self.movement_frame)
        self.left_pushButton.setGeometry(QtCore.QRect(20, 60, 50, 50))
        self.left_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#153b47;\n"
"border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.left_pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("PyQt6\\Mega_Project_GUI\\icons\\arrow_left.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.left_pushButton.setIcon(icon4)
        self.left_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.left_pushButton.setCheckable(False)
        self.left_pushButton.setChecked(False)
        self.left_pushButton.setAutoRepeat(False)
        self.left_pushButton.setAutoExclusive(False)
        self.left_pushButton.setDefault(False)
        self.left_pushButton.setFlat(False)
        self.left_pushButton.setObjectName("left_pushButton")
        self.frame = QtWidgets.QFrame(parent=self.control_tab)
        self.frame.setGeometry(QtCore.QRect(630, 250, 120, 120))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(9, 15, 19);\n"
"border-radius:60px;\n"
"}\n"
"QPushButton{\n"
"background-color:rgb(255, 42, 56);\n"
"border-radius:50px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(230, 176, 38);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Stop_car_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.Stop_car_pushButton.setGeometry(QtCore.QRect(10, 10, 100, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.Stop_car_pushButton.setFont(font)
        self.Stop_car_pushButton.setStyleSheet("color: rgb(255, 255, 255);")
        self.Stop_car_pushButton.setObjectName("Stop_car_pushButton")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("PyQt6\\Mega_Project_GUI\\icons\\control_icon_black.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap("PyQt6\\Mega_Project_GUI\\icons\\control_Icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.maintabs_Widget.addTab(self.control_tab, icon5, "")
        self.camera_tab = QtWidgets.QWidget()
        self.camera_tab.setObjectName("camera_tab")
        self.camera_label = QtWidgets.QLabel(parent=self.camera_tab)
        self.camera_label.setGeometry(QtCore.QRect(30, 30, 741, 411))
        self.camera_label.setStyleSheet("background-color: rgb(61, 96, 110);")
        self.camera_label.setText("")
        self.camera_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.camera_label.setObjectName("camera_label")
        self.camera_buttons_frame = QtWidgets.QFrame(parent=self.camera_tab)
        self.camera_buttons_frame.setGeometry(QtCore.QRect(70, 450, 670, 100))
        self.camera_buttons_frame.setStyleSheet("background:#090f13;\n"
"border-radius:50px;")
        self.camera_buttons_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.camera_buttons_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.camera_buttons_frame.setObjectName("camera_buttons_frame")
        self.screenshot_frame = QtWidgets.QFrame(parent=self.camera_buttons_frame)
        self.screenshot_frame.setGeometry(QtCore.QRect(300, 10, 81, 61))
        self.screenshot_frame.setStyleSheet("border-radius:30;\n"
"background-color:white;")
        self.screenshot_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.screenshot_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.screenshot_frame.setObjectName("screenshot_frame")
        self.screenshot_pushButton = QtWidgets.QPushButton(parent=self.screenshot_frame)
        self.screenshot_pushButton.setGeometry(QtCore.QRect(20, 10, 40, 40))
        self.screenshot_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#3d606e;\n"
"border-radius:20px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.screenshot_pushButton.setText("")
        self.screenshot_pushButton.setCheckable(True)
        self.screenshot_pushButton.setObjectName("screenshot_pushButton")
        self.stop_pushButton = QtWidgets.QPushButton(parent=self.camera_buttons_frame)
        self.stop_pushButton.setGeometry(QtCore.QRect(430, 30, 140, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.stop_pushButton.setFont(font)
        self.stop_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#3d606e;\n"
"color:white;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.stop_pushButton.setCheckable(True)
        self.stop_pushButton.setAutoExclusive(True)
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.start_pushButton = QtWidgets.QPushButton(parent=self.camera_buttons_frame)
        self.start_pushButton.setGeometry(QtCore.QRect(110, 30, 140, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.start_pushButton.setFont(font)
        self.start_pushButton.setStyleSheet("QPushButton{\n"
"background-color:#3d606e;\n"
"color:white;\n"
"border-radius:15px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: rgb(230, 176, 38);\n"
"}\n"
"")
        self.start_pushButton.setCheckable(True)
        self.start_pushButton.setChecked(False)
        self.start_pushButton.setAutoExclusive(True)
        self.start_pushButton.setObjectName("start_pushButton")
        self.screenshot_label = QtWidgets.QLabel(parent=self.camera_buttons_frame)
        self.screenshot_label.setGeometry(QtCore.QRect(300, 70, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        self.screenshot_label.setFont(font)
        self.screenshot_label.setStyleSheet("background:none;\n"
"color:white;")
        self.screenshot_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.screenshot_label.setObjectName("screenshot_label")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("PyQt6\\Mega_Project_GUI\\icons\\camera_icon_black.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon6.addPixmap(QtGui.QPixmap("PyQt6\\Mega_Project_GUI\\icons\\camera_Icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.maintabs_Widget.addTab(self.camera_tab, icon6, "")
        self.gridLayout.addWidget(self.maintabs_Widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.maintabs_Widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main Control"))
        self.StereoVision_pushButton.setText(_translate("MainWindow", "Go to Stereo Vision"))
        self.credits_pushButton.setText(_translate("MainWindow", "Credits"))
        self.videoStitching_pushButton.setText(_translate("MainWindow", "Go to Video Stitching"))
        self.welcome_label.setText(_translate("MainWindow", "Welcome to Bar2 Banzeen Control Station"))
        self.maintabs_Widget.setTabText(self.maintabs_Widget.indexOf(self.home_tab), _translate("MainWindow", "Home"))
        self.mode_label.setText(_translate("MainWindow", "select mode"))
        self.autonomus_mode_pushButton.setText(_translate("MainWindow", "Autonomous"))
        self.manual_mode_pushButton.setText(_translate("MainWindow", "Manual"))
        self.select_speed_label.setText(_translate("MainWindow", "Select speed"))
        self.high_speed_pushButton.setText(_translate("MainWindow", "High"))
        self.medium_speed_pushButton.setText(_translate("MainWindow", "Medium"))
        self.low_speed_pushButton.setText(_translate("MainWindow", "Low"))
        self.select_controller_label.setText(_translate("MainWindow", "Select Controller "))
        self.keyboard_pushButton.setText(_translate("MainWindow", "Keyboard"))
        self.GUI_pushButton.setText(_translate("MainWindow", "GUI "))
        self.voltage_label.setText(_translate("MainWindow", "- Voltage:"))
        self.current_label.setText(_translate("MainWindow", "- Current:"))
        self.speen_label.setText(_translate("MainWindow", "- Speed:"))
        self.speed_reading.setText(_translate("MainWindow", "N"))
        self.mode_indicator.setText(_translate("MainWindow", "- Mode:"))
        self.mode_reading.setText(_translate("MainWindow", "N"))
        self.voltage_reading.setText(_translate("MainWindow", "N/A"))
        self.current_reading.setText(_translate("MainWindow", "N/A"))
        self.distance_label.setText(_translate("MainWindow", "- Distance:"))
        self.direction_label.setText(_translate("MainWindow", "- Direction:"))
        self.direction_reading.setText(_translate("MainWindow", "N"))
        self.distance_reading.setText(_translate("MainWindow", "N/A"))
        self.connection_label.setText(_translate("MainWindow", "- Connection:"))
        self.controller_label.setText(_translate("MainWindow", "- Controller:"))
        self.connection_reading.setText(_translate("MainWindow", "N/A"))
        self.controller_reading.setText(_translate("MainWindow", "N/A"))
        self.indicator_label.setText(_translate("MainWindow", "Indicators"))
        self.Stop_car_pushButton.setText(_translate("MainWindow", "Stop"))
        self.maintabs_Widget.setTabText(self.maintabs_Widget.indexOf(self.control_tab), _translate("MainWindow", "Control"))
        self.stop_pushButton.setText(_translate("MainWindow", "stop"))
        self.start_pushButton.setText(_translate("MainWindow", "Start"))
        self.screenshot_label.setText(_translate("MainWindow", "Screenshot"))
        self.maintabs_Widget.setTabText(self.maintabs_Widget.indexOf(self.camera_tab), _translate("MainWindow", "Camera"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
