# Form implementation generated from reading ui file 'PyQt6\Mega_Project_GUI\StereoVision.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StereoVision(object):
    def setupUi(self, StereoVision):
        StereoVision.setObjectName("StereoVision")
        StereoVision.resize(717, 518)
        StereoVision.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0648899 rgba(9, 15, 19, 255), stop:0.571233 rgba(21, 59, 71, 255), stop:0.890411 rgba(61, 96, 110, 255));")
        self.info_frame = QtWidgets.QFrame(parent=StereoVision)
        self.info_frame.setGeometry(QtCore.QRect(20, 20, 311, 231))
        self.info_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(61, 96, 110);\n"
"border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(9, 15, 19);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    background-color: rgb(230, 201, 39);\n"
"}")
        self.info_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.info_frame.setObjectName("info_frame")
        self.label_5 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 49, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_6.setGeometry(QtCore.QRect(20, 70, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.cam0 = QtWidgets.QLineEdit(parent=self.info_frame)
        self.cam0.setGeometry(QtCore.QRect(70, 16, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cam0.setFont(font)
        self.cam0.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cam0.setInputMask("")
        self.cam0.setClearButtonEnabled(False)
        self.cam0.setObjectName("cam0")
        self.cam1 = QtWidgets.QLineEdit(parent=self.info_frame)
        self.cam1.setGeometry(QtCore.QRect(70, 66, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cam1.setFont(font)
        self.cam1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cam1.setObjectName("cam1")
        self.label_7 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_8.setGeometry(QtCore.QRect(170, 120, 49, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.baseline = QtWidgets.QLineEdit(parent=self.info_frame)
        self.baseline.setGeometry(QtCore.QRect(80, 122, 81, 21))
        self.baseline.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.baseline.setObjectName("baseline")
        self.num_disp = QtWidgets.QLineEdit(parent=self.info_frame)
        self.num_disp.setGeometry(QtCore.QRect(220, 122, 81, 21))
        self.num_disp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_disp.setObjectName("num_disp")
        self.label_9 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_9.setGeometry(QtCore.QRect(10, 160, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.info_frame)
        self.label_10.setGeometry(QtCore.QRect(165, 160, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.height = QtWidgets.QLineEdit(parent=self.info_frame)
        self.height.setGeometry(QtCore.QRect(70, 162, 85, 21))
        self.height.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.height.setObjectName("height")
        self.width = QtWidgets.QLineEdit(parent=self.info_frame)
        self.width.setGeometry(QtCore.QRect(220, 162, 81, 21))
        self.width.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.width.setObjectName("width")
        self.start_stereo_pushButton = QtWidgets.QPushButton(parent=self.info_frame)
        self.start_stereo_pushButton.setGeometry(QtCore.QRect(110, 190, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.start_stereo_pushButton.setFont(font)
        self.start_stereo_pushButton.setObjectName("start_stereo_pushButton")
        self.frame = QtWidgets.QFrame(parent=StereoVision)
        self.frame.setGeometry(QtCore.QRect(350, 20, 351, 91))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(61, 96, 110);\n"
"    border-radius:20px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.rightOpen_stereo_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.rightOpen_stereo_pushButton.setGeometry(QtCore.QRect(200, 40, 75, 24))
        font = QtGui.QFont()
        font.setBold(True)
        self.rightOpen_stereo_pushButton.setFont(font)
        self.rightOpen_stereo_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(9, 15, 19);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    background-color: rgb(230, 201, 39);\n"
"}")
        self.rightOpen_stereo_pushButton.setObjectName("rightOpen_stereo_pushButton")
        self.right_ = QtWidgets.QLabel(parent=self.frame)
        self.right_.setGeometry(QtCore.QRect(185, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.right_.setFont(font)
        self.right_.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:none;")
        self.right_.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.right_.setObjectName("right_")
        self.leftOpen_stereo_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.leftOpen_stereo_pushButton.setGeometry(QtCore.QRect(55, 40, 75, 24))
        font = QtGui.QFont()
        font.setBold(True)
        self.leftOpen_stereo_pushButton.setFont(font)
        self.leftOpen_stereo_pushButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(9, 15, 19);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    background-color: rgb(230, 201, 39);\n"
"}")
        self.leftOpen_stereo_pushButton.setObjectName("leftOpen_stereo_pushButton")
        self.left_text_label = QtWidgets.QLabel(parent=self.frame)
        self.left_text_label.setGeometry(QtCore.QRect(40, 10, 100, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.left_text_label.setFont(font)
        self.left_text_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background:none;")
        self.left_text_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.left_text_label.setObjectName("left_text_label")
        self.scrollArea = QtWidgets.QScrollArea(parent=StereoVision)
        self.scrollArea.setGeometry(QtCore.QRect(20, 270, 681, 231))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 678, 518))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.photo_back_frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.photo_back_frame.setMinimumSize(QtCore.QSize(660, 500))
        self.photo_back_frame.setStyleSheet("background:none;")
        self.photo_back_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.photo_back_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.photo_back_frame.setObjectName("photo_back_frame")
        self.image_label = QtWidgets.QLabel(parent=self.photo_back_frame)
        self.image_label.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.image_label.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.CrossCursor))
        self.image_label.setMouseTracking(True)
        self.image_label.setTabletTracking(False)
        self.image_label.setStyleSheet("background-color: rgb(61, 96, 110);")
        self.image_label.setText("")
        self.image_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.verticalLayout.addWidget(self.photo_back_frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_3 = QtWidgets.QFrame(parent=StereoVision)
        self.frame_3.setGeometry(QtCore.QRect(350, 120, 351, 131))
        self.frame_3.setStyleSheet("QFrame{\n"
"background-color: rgb(61, 96, 110);\n"
"border-radius:20px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(100, 100, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(140, 0, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lenght = QtWidgets.QLabel(parent=self.frame_3)
        self.lenght.setGeometry(QtCore.QRect(180, 100, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.lenght.setFont(font)
        self.lenght.setStyleSheet("color: rgb(255, 255, 255);")
        self.lenght.setObjectName("lenght")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(20, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(20, 70, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setObjectName("label_12")
        self.point1 = QtWidgets.QLabel(parent=self.frame_3)
        self.point1.setGeometry(QtCore.QRect(90, 40, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.point1.setFont(font)
        self.point1.setStyleSheet("color: rgb(255, 255, 255);")
        self.point1.setObjectName("point1")
        self.point2 = QtWidgets.QLabel(parent=self.frame_3)
        self.point2.setGeometry(QtCore.QRect(90, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.point2.setFont(font)
        self.point2.setStyleSheet("color: rgb(255, 255, 255);")
        self.point2.setObjectName("point2")

        self.retranslateUi(StereoVision)
        QtCore.QMetaObject.connectSlotsByName(StereoVision)

    def retranslateUi(self, StereoVision):
        _translate = QtCore.QCoreApplication.translate
        StereoVision.setWindowTitle(_translate("StereoVision", "Dialog"))
        self.label_5.setText(_translate("StereoVision", "Cam0:"))
        self.label_6.setText(_translate("StereoVision", "Cam1:"))
        self.label_7.setText(_translate("StereoVision", "baseline:"))
        self.label_8.setText(_translate("StereoVision", "ndisp:"))
        self.label_9.setText(_translate("StereoVision", "Height:"))
        self.label_10.setText(_translate("StereoVision", "Width:"))
        self.start_stereo_pushButton.setText(_translate("StereoVision", "Start"))
        self.rightOpen_stereo_pushButton.setText(_translate("StereoVision", "Open File"))
        self.right_.setText(_translate("StereoVision", "Right Image"))
        self.leftOpen_stereo_pushButton.setText(_translate("StereoVision", "Open File"))
        self.left_text_label.setText(_translate("StereoVision", " Left Image"))
        self.label_2.setText(_translate("StereoVision", "Length:"))
        self.label_3.setText(_translate("StereoVision", "output"))
        self.lenght.setText(_translate("StereoVision", "0px"))
        self.label_11.setText(_translate("StereoVision", "point1 ="))
        self.label_12.setText(_translate("StereoVision", "Point2 ="))
        self.point1.setText(_translate("StereoVision", "(X1,Y1)"))
        self.point2.setText(_translate("StereoVision", "(X2,Y2)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StereoVision = QtWidgets.QDialog()
    ui = Ui_StereoVision()
    ui.setupUi(StereoVision)
    StereoVision.show()
    sys.exit(app.exec())
